### ISSUE TITLE
Migrate to Harmony

### ISSUE THREAD

**Issue by dymanoid** [algernon-A/Realistic-Population-Revisited#1]
The patching method used in this mod is deprecated and unsafe.

Most of the mods are using the [Harmony library](https://github.com/pardeike/Harmony) ([NuGet](https://www.nuget.org/packages/Lib.Harmony/1.2.0.1)).

You should consider migrating to the Harmony library to ensure the safe and non-destructing method paching.

Note: do not use the version 2.x of the library, it is runtime-incompatible with the 1.x versions most mods are currently using.

**Comment by algernon-A** [comment]
Agreed - Harmony migration is definitely a must-do.

**Comment by algernon-A** [comment]
Fixed by 59ee864bdf1e35fb14fd6202793a3eba2e661706
