### ISSUE TITLE
Nothing seams to affect specialized industrial building

### ISSUE THREAD

**Issue by ikus060** [algernon-A/Realistic-Population-Revisited#25]
When building a farm, the number of worker seams way to high to be realistic.
I tried to change the settings using this mod and nothing seams to affect this 20 worker for a small crop field.

![image](https://user-images.githubusercontent.com/921251/131219706-ed27204f-bcc2-4863-a409-29d500ad6e5b.png)

**Comment by algernon-A** [comment]
That is an industries DLC field (player industry AI), and so is not covered by this mod; this mod only adjusts the figures for private AI buildings.

See the reply on the Steam discussion thread for a link to a mod that does what you want.
