### ISSUE TITLE
Simulation error: Could not load type 'Problem'.

### ISSUE THREAD

**Issue by SuryaRajgor** [algernon-A/Realistic-Population-Revisited#37]
if the game is paused its no error but when starting the simulation it continues to popup error (old save)
 and start a new game then its works fine until a new residential building is created or build 
 
[output_log.txt](https://github.com/algernon-A/Realistic-Population-Revisited/files/10349602/output_log.txt)

**Comment by algernon-A** [comment]
You have an outdated and broken mod, that's trying to load a data type that was removed from the game with the 1.15 update.  Remove it, and things will work fine.

**Comment by SuryaRajgor** [comment]
I have a epic version so, i downloaded it from the workshop can you tell me how to compile the latest or how to get it??

**Comment by SuryaRajgor** [comment]
ok thanks got it.
