### ISSUE TITLE
Error occurred when loading

### ISSUE THREAD

**Issue by zengfanfan** [algernon-A/Realistic-Population-Revisited#41]
The Mod `xxx` [0Harmony.dll, RealPopRevisited.dll] has caused an error [ModException]

Details:
System.ArgumentException: No target method specified for class RealisticPopulationRevisited.RealisticCitizenUnits (declaringType=BuildingAI, methodName =EnsureCitizenUnits, methodType=, argumentTypes=(System.UInt16, Building

**Comment by algernon-A** [comment]
That's caused by not using the latest version of the mod (2.2.3) with the latest game version (1.17).  Make sure that you are using mod version 2.2.3.

**Comment by zengfanfan** [comment]
correct.
fixed.
thx.
