### ISSUE TITLE
Number of visitors shown on ZonedBuildingWorldInfoPanel is wrong

### ISSUE THREAD

**Issue by Infixo** [algernon-A/Realistic-Population-Revisited#42]
You use GetVisitBehaviour() to get the visitor count however it returns 2 values: aliveCount and totalCount. The mod displays totalCount which imo is wrong because it also includes dead people (duh!) and ones that on the move.
You can drill down to GetCitizenVisitBehaviour and see that actual visitors, the ones used later to calculate average wealth of visitors, are stored in aliveCount.

**Comment by algernon-A** [comment]
I'm aware of all that, thanks.  TotalCount is used deliberately as that's what's appropriate here, which is presenting available capacity (and this mod is all about capacity as its focus).

**Comment by Infixo** [comment]
Not sure if I presented the issue correctly. I am talking about ZonedBuilding info view, showing what happens atm. It's ok for presenting this as "total capacity" (assuming that dead people consume it, idk the logic here) but not ok for counting as actual visitors. The mod shows dead people now as vistors.

**Comment by algernon-A** [comment]
The mod simply shows the total number of visitor spaces vs. the current usage of those spaces for the purposes of building capacity and utilization, which is what this mod is about.  The status of an assigned visitor is irrelevant for the purpose of this mod.  I think you want a different mod, one which provides detailed info on visitors - this mod is just about building capacities.

**Comment by Infixo** [comment]
If you don't want to fix it (which is literally 1 word) then just say so. Please don't rationalize absurd logic.
RPR changes the capacity. But the game still counts separately dead people and they are not visitors.
The mod adds this misleading info. Maybe better not add it at all, and leave it just as the game is designed, instead of giving false info.

**Comment by Infixo** [comment]
And if you want RPR to be "just about capacities" then don't add info about visitors.

**Comment by algernon-A** [comment]
Do you honestly not understand how visitor capacities work, and how they're calculated?  Visitor capacities are definitely part of this mod.
