### ISSUE TITLE
Get compiled version for 1.17.0-f3 (2.2.1)

### ISSUE THREAD

**Issue by surister** [algernon-A/Realistic-Population-Revisited#43]
Hi, I'm running a long game for 1.17.0-f3 I cannot update my game because not every mod I use has updated to 1.17.2, and steam does not allow for different versions download, any chance you could share the compiled version for .2.2.1

**Comment by algernon-A** [comment]
Only the current game version is supported, and this is not subject to change or negotiation.

**Comment by surister** [comment]
Well, If you don't mind I will fork and release the versions myself :)
