### ISSUE TITLE
Farming with total floor area 0 always "not operating"

### ISSUE THREAD

**Issue by Hantei** [algernon-A/Realistic-Population-Revisited#44]
Issue only occurs with specialised industrial areas which have 0 floor area. Possibly with other industry types as well. Could be some range, of course, but I only noticed it with 0 floor area instances.
![image](https://github.com/user-attachments/assets/62b916d8-22cf-404c-b471-c9d4a8db737b)
![image](https://github.com/user-attachments/assets/2265f50e-6cbf-43e2-8883-9576cb7b6027)

**Comment by algernon-A** [comment]
That appears to be the normal 'not operating' phase for part of the day for industrial extractors.  Can you confirm otherwise?

**Comment by Hantei** [comment]
Tested with "Oil2x2". It appears "not operating" for majority of the cycle. "Operating normally" appears for about 1-2 seconds regardless of game speed, about every 14ish in game days. No difference between daytime or night time. Is this how it's supposed to be?

**Comment by algernon-A** [comment]
The exact ratio of operating to non-operating will depend on how much production the game has calculated for that industry.

**Comment by Hantei** [comment]
If this is intended mechanic, then apologies for the alarm :). Struck me as strange seeing all my farmland "not operating", except for lands with buildings.

**Comment by algernon-A** [comment]
Agreed, it's not very intuitive, and you're not the first to be confused by it :)  For better or worse, that's how the game operates with the extractors.  Adding some more staff _might_ help, depending upon the specifics of the industry, but more commonly the limiting factor is the base resource extraction limit.
